# -*- coding: utf-8 -*-
"""dictionary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1btNTBNUVAL-pqlRiasQ2ATISK5I-0rck
"""

a={'name':'helo','roll no.':3}
a.clear()
print(a)

a={'institution':'regex',
'coarse':'data science',
'trainer':'tushar',
'hr':'karishma'}
b=a.copy()
print(b)

a={'institution':'regex',
'coarse':'data science',
'trainer':'tushar',
'hr':'karishma'}
a.pop('coarse')
print(a)

b={'institution':'regex',
'coarse':'data science',
'trainer':'tushar',
'hr':'karishma'}
b['age']=25
print(b)
b.pop('coarse')
print(b)
b.keys()
b.values()
b.items()
for keys in b:
  print(keys)
for values in b:
  print(values)

b.len()